import express from 'express';
import { getBlogs, getBlog, createBlog, updateBlog, deleteBlog } from '../controllers/blogController.js';
import { protect } from '../middleware/auth.js';
const router = express.Router();
router.get('/', (req, res, next) => { req.admin = null; next(); }, getBlogs);
router.get('/:slug', getBlog);
router.post('/', protect, createBlog);
router.put('/:id', protect, updateBlog);
router.delete('/:id', protect, deleteBlog);
export default router;
